const types = {
    NUEVA_NOVEDAD: 'NUEVA_NOVEDAD',
    NUEVA_NOVEDAD_SUCCESS: 'NUEVA_NOVEDAD_SUCCESS',
    NUEVA_NOVEDAD_ERROR: 'NUEVA_NOVEDAD_ERROR',

    CLEAR_STATUS: 'CLEAR_STATUS',

    GET_ENLACES_NOVEDADES: 'GET_ENLACES_NOVEDADES',
    GET_ENLACES_NOVEDADES_SUCCESS: 'GET_ENLACES_NOVEDADES_SUCCESS',
    GET_ENLACES_NOVEDADES_ERROR: 'GET_ENLACES_NOVEDADES_ERROR',

    CLEAR_ENLACES_NOVEDADES: 'CLEAR_ENLACES_NOVEDADES'
}

export default types