// src/redux/reducers/novedades/types.js
const types = {
    // === CREAR ===
    NUEVA_NOVEDAD: 'NUEVA_NOVEDAD',
    NUEVA_NOVEDAD_SUCCESS: 'NUEVA_NOVEDAD_SUCCESS',
    NUEVA_NOVEDAD_ERROR: 'NUEVA_NOVEDAD_ERROR',

    // === SUBIR IMAGEN ===
    UPLOAD_IMG: 'UPLOAD_IMG',
    UPLOAD_IMG_SUCCESS: 'UPLOAD_IMG_SUCCESS',
    UPLOAD_IMG_ERROR: 'UPLOAD_IMG_ERROR',
    UPLOAD_PROGRESS: 'UPLOAD_PROGRESS',

    // === EDITAR ===
    UPLOAD_NOVEDAD: 'UPLOAD_NOVEDAD',
    UPLOAD_NOVEDAD_SUCCESS: 'UPLOAD_NOVEDAD_SUCCESS',
    UPLOAD_NOVEDAD_ERROR: 'UPLOAD_NOVEDAD_ERROR',

    // === LISTAR ===
    GET_NOVEDADES: 'GET_NOVEDADES',
    GET_NOVEDADES_SUCCESS: 'GET_NOVEDADES_SUCCESS',
    GET_NOVEDADES_ERROR: 'GET_NOVEDADES_ERROR',

    // === LISTAR (para usuario, si lo usás en el front público) ===
    GET_NOVEDADES_USER: 'GET_NOVEDADES_USER',
    GET_NOVEDADES_USER_SUCCESS: 'GET_NOVEDADES_USER_SUCCESS',
    GET_NOVEDADES_USER_ERROR: 'GET_NOVEDADES_USER_ERROR',

    // === DETALLE ===
    GET_NOVEDAD: 'GET_NOVEDAD',

    // === ELIMINAR ===
    DELETE_NOVEDADES: 'DELETE_NOVEDADES',
    DELETE_NOVEDADES_SUCCESS: 'DELETE_NOVEDADES_SUCCESS',
    DELETE_NOVEDADES_ERROR: 'DELETE_NOVEDADES_ERROR',

    // === PAGINACIÓN ===
    SET_FIRST_NOVEDAD: 'SET_FIRST_NOVEDAD',
    SET_LAST_NOVEDAD: 'SET_LAST_NOVEDAD',
    SET_PAGE_NOVEDAD: 'SET_PAGE_NOVEDAD',

    // === LIMPIEZAS ===
    CLEAR_STATUS: 'CLEAR_STATUS',
    CLEAR_NOVEDADES: 'CLEAR_NOVEDADES',
};

export default types;
