// USER TYPES
export const GET_CUOTAS = 'GET_CUOTAS'
export const GET_CUOTAS_SUCCESS = 'GET_CUOTAS_SUCCESS'
export const GET_CUOTAS_ERROR = 'GET_CUOTAS_ERROR'

export const POST_TRANSACTION = 'POST_TRANSACTION'
export const POST_TRANSACTION_SUCCESS = 'POST_TRANSACTION_SUCCESS'
export const POST_TRANSACTION_ERROR = 'POST_TRANSACTION_ERROR'

export const SET_USER_CUOTAS = 'SET_USER_CUOTAS'
export const SET_USER_CUOTAS_SUCCESS = 'SET_USER_CUOTAS_SUCCESS'
export const SET_USER_CUOTAS_ERROR = 'SET_USER_CUOTAS_ERROR'

export const SET_USER_SESSION = 'SET_USER_SESSION';

export const CLEAR_USER_STATUS = 'CLEAR_PROFILE_STATUS';
export const APROVE = 'APROVE';


