// USER TYPES
export const NUEVA_CUOTA = 'NUEVA_CUOTA'
export const NUEVA_CUOTA_SUCCESS = 'NUEVA_CUOTA_SUCCESS'
export const NUEVA_CUOTA_ERROR = 'NUEVA_CUOTA_ERROR'

export const UPLOAD_CUOTA = 'UPLOAD_CUOTA';
export const UPLOAD_CUOTA_SUCCESS = 'UPLOAD_CUOTA_SUCCESS';
export const UPLOAD_CUOTA_ERROR = 'UPLOAD_CUOTA_ERROR';

export const GET_CUOTAS = 'GET_CUOTAS'
export const GET_CUOTAS_SUCCESS = 'GET_CUOTAS_SUCCESS'
export const GET_CUOTAS_ERROR = 'GET_CUOTAS_ERROR'

export const SET_USER_CUOTAS = 'SET_USER_CUOTAS'
export const SET_USER_CUOTAS_SUCCESS = 'SET_USER_CUOTAS_SUCCESS'
export const SET_USER_CUOTAS_ERROR = 'SET_USER_CUOTAS_ERROR'

export const SET_USER_SESSION = 'SET_USER_SESSION';

export const CLEAR_CUOTAS_STATUS = 'CLEAR_CUOTAS_STATUS';
export const APROVE = 'APROVE';


