export const NUEVA_TRANSACCION = 'NUEVA_TRANSACCION'
export const NUEVA_TRANSACCION_SUCCESS = 'NUEVA_TRANSACCION_SUCCESS'
export const NUEVA_TRANSACCION_ERROR = 'NUEVA_TRANSACCION_ERROR'

export const GET_TRANSACCIONES = 'GET_TRANSACCIONES'
export const GET_TRANSACCIONES_SUCCESS = 'GET_TRANSACCIONES_SUCCESS'
export const GET_TRANSACCIONES_ERROR = 'GET_TRANSACCIONES_ERROR'

export const GET_USER_CUOTAS = 'GET_USER_CUOTAS'
export const GET_USER_CUOTAS_SUCCESS = 'GET_USER_CUOTAS_SUCCESS'
export const GET_USER_CUOTAS_ERROR = 'GET_USER_CUOTAS_ERROR'

export const CLEAR_TRANSACCIONES_STATUS = 'CLEAR_TRANSACCIONES_STATUS';


