const types = {
    NUEVO_ASESORAMIENTO: 'NUEVO_ASESORAMIENTO',
    NUEVO_ASESORAMIENTO_SUCCESS: 'NUEVO_ASESORAMIENTO_SUCCESS',
    NUEVO_ASESORAMIENTO_ERROR: 'NUEVO_ASESORAMIENTO_ERROR',

    CLEAR_STATUS: 'CLEAR_STATUS',
}

export default types