const types = {
    NUEVO_ASESORAMIENTO: 'NUEVO_ASESORAMIENTO',
    NUEVO_ASESORAMIENTO_SUCCESS: 'NUEVO_ASESORAMIENTO_SUCCESS',
    NUEVO_ASESORAMIENTO_ERROR: 'NUEVO_ASESORAMIENTO_ERROR',

    CLEAR_STATUS: 'CLEAR_STATUS',

    GET_ENLACES_ASESORAMIENTO: 'GET_ENLACES_ASESORAMIENTO',
    GET_ENLACES_ASESORAMIENTO_SUCCESS: 'GET_ENLACES_ASESORAMIENTO_SUCCESS',
    GET_ENLACES_ASESORAMIENTO_ERROR: 'GET_ENLACES_ASESORAMIENTO_ERROR',

    SET_CATEGORIA: 'SET_CATEGORIA',
    SET_LAST_DOC_ASESORAMIENTO: 'SET_LAST_DOC_ASESORAMIENTO',
    SET_NO_MORE_DATA_ASESORAMIENTO: 'SET_NO_MORE_DATA_ASESORAMIENTO',
    CLEAR_ENLACES_ASESORAMIENTO: 'CLEAR_ENLACES_ASESORAMIENTO'
}

export default types