const types = {

    NUEVO_CURSO: 'NUEVO_CURSO',
    NUEVO_CURSO_SUCCESS: 'NUEVO_CURSO_SUCCESS',
    NUEVO_CURSO_ERROR: 'NUEVO_CURSO_ERROR',

    UPLOAD_IMG: 'UPLOAD_IMG',
    UPLOAD_IMG_SUCCESS: 'UPLOAD_IMG_SUCCESS',
    UPLOAD_IMG_ERROR: 'UPLOAD_IMG_ERROR',

    UPLOAD_PROGRESS: 'UPLOAD_PROGRESS',

    CLEAR_STATUS: 'CLEAR_STATUS',

    UPLOAD_CURSO: 'UPLOAD_CURSO',
    UPLOAD_CURSO_SUCCESS: 'UPLOAD_CURSO_SUCCESS',
    UPLOAD_CURSO_ERROR: 'UPLOAD_CURSO_ERROR',

    GET_CURSOS_USER: 'GET_CURSOS_USER',
    GET_CURSOS_USER_SUCCESS: 'GET_CURSOS_USER_SUCCESS',
    GET_CURSOS_USER_ERROR: 'GET_CURSOS_USER_ERROR',

    GET_CURSOS: 'GET_CURSOS',
    GET_CURSOS_SUCCESS: 'GET_CURSOS_SUCCESS',
    GET_CURSOS_ERROR: 'GET_CURSOS_ERROR',

    CLEAR_CURSOS: 'CLEAR_CURSOS',

    SET_FIRST_CURSO: 'SET_FIRST_CURSO',
    SET_LAST_CURSO: 'SET_LAST_CURSO',
    SET_PAGE: 'SET_PAGE',

    GET_CURSO: 'GET_CURSO'
}

export default types