const types = {

    NUEVO_CURSO: 'NUEVO_CURSO',
    NUEVO_CURSO_SUCCESS: 'NUEVO_CURSO_SUCCESS',
    NUEVO_CURSO_ERROR: 'NUEVO_CURSO_ERROR',

    UPLOAD_IMG: 'UPLOAD_IMG',
    UPLOAD_IMG_SUCCESS: 'UPLOAD_IMG_SUCCESS',
    UPLOAD_IMG_ERROR: 'UPLOAD_IMG_ERROR',

    UPLOAD_PROGRESS: 'UPLOAD_PROGRESS',

    CLEAR_STATUS: 'CLEAR_STATUS',

    UPLOAD_CURSO: 'UPLOAD_CURSO',
    UPLOAD_CURSO_SUCCESS: 'UPLOAD_CURSO_SUCCESS',
    UPLOAD_CURSO_ERROR: 'UPLOAD_CURSO_ERROR',

    GET_CURSOS: 'GET_CURSOS',
    GET_CURSOS_SUCCESS: 'GET_CURSOS_SUCCESS',
    GET_CURSOS_ERROR: 'GET_CURSOS_ERROR',

    // 👉 Nuevos para cursos disponibles
    GET_CURSOS_DISPONIBLES: 'GET_CURSOS_DISPONIBLES',
    GET_CURSOS_DISPONIBLES_SUCCESS: 'GET_CURSOS_DISPONIBLES_SUCCESS',
    GET_CURSOS_DISPONIBLES_ERROR: 'GET_CURSOS_DISPONIBLES_ERROR',

    SET_FIRST_CURSO: 'SET_FIRST_CURSO',
    SET_LAST_CURSO: 'SET_LAST_CURSO',
    SET_PAGE_CURSO: 'SET_PAGE_CURSO',

    GET_CURSOS_CATEGORY: 'GET_CURSOS_CATEGORY',
    GET_CURSOS_CATEGORY_SUCCESS: 'GET_CURSOS_CATEGORY_SUCCESS',
    GET_CURSOS_CATEGORY_ERROR: 'GET_CURSOS_CATEGORY_ERROR',

    GET_MIS_CURSOS: 'GET_MIS_CURSOS',
    GET_MIS_CURSOS_SUCCESS: 'GET_MIS_CURSOS_SUCCESS',
    GET_MIS_CURSOS_ERROR: 'GET_MIS_CURSOS_ERROR',

    DELETE_CURSOS: 'DELETE_CURSOS',
    DELETE_CURSOS_SUCCESS: 'DELETE_CURSOS_SUCCESS',
    DELETE_CURSOS_ERROR: 'DELETE_CURSOS_ERROR',

    UPLOAD_CURSOS_USER_INFO: 'UPLOAD_CURSOS_USER_INFO',
    UPLOAD_CURSOS_USER_INFO_SUCCESS: 'UPLOAD_CURSOS_USER_INFO_SUCCESS',
    UPLOAD_CURSOS_USER_INFO_ERROR: 'UPLOAD_CURSOS_USER_INFO_ERROR',

    GET_CURSO: 'GET_CURSO',
    CLEAR_CURSOS: 'CLEAR_CURSOS',
}

export default types
