const types = {

    NUEVO_CURSO: 'NUEVO_CURSO',
    NUEVO_CURSO_SUCCESS: 'NUEVO_CURSO_SUCCESS',
    NUEVO_CURSO_ERROR: 'NUEVO_CURSO_ERROR',

    UPLOAD_IMG: 'UPLOAD_IMG',
    UPLOAD_IMG_SUCCESS: 'UPLOAD_IMG_SUCCESS',
    UPLOAD_IMG_ERROR: 'UPLOAD_IMG_ERROR',

    UPLOAD_PROGRESS: 'UPLOAD_PROGRESS',

    CLEAR_STATUS: 'CLEAR_STATUS',

    GET_CURSOS_USER: 'GET_CURSOS_USER',
    GET_CURSOS_USER_SUCCESS: 'GET_CURSOS_USER_SUCCESS',
    GET_CURSOS_USER_ERROR: 'GET_CURSOS_USER_ERROR',

    GET_CURSOS: 'GET_CURSOS',
    GET_CURSOS_SUCCESS: 'GET_CURSOS_SUCCESS',
    GET_CURSOS_ERROR: 'GET_CURSOS_ERROR',

    SET_LAST_DOC_CURSOS_MIS_CURSOS: 'SET_LAST_DOC_CURSOS_MIS_CURSOS',
    SET_LAST_DOC_CURSOS: 'SET_LAST_DOC_CURSOS',
    SET_NO_MORE_DATA_CURSOS: 'SET_NO_MORE_DATA_CURSOS',

    SET_PAGE_NAME: 'SET_PAGE_NAME',
    CLEAR_CURSOS: 'CLEAR_CURSOS',
}

export default types