const types = {
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    AUTHENTICATE_USER_SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
    AUTHENTICATE_USER_ERROR: 'AUTHENTICATE_USER_ERROR',

    NEW_USER: 'NEW_USER',
    NEW_USER_SUCCESS: 'NEW_USER_SUCCESS',
    NEW_USER_ERROR: 'NEW_USER_ERROR',

    GET_AFILIADOS_NUEVOS: 'GET_AFILIADOS_NUEVOS',
    GET_AFILIADOS_NUEVOS_SUCCESS: 'GET_AFILIADOS_NUEVOS_SUCCESS',
    GET_AFILIADOS_NUEVOS_ERROR: 'GET_AFILIADOS_NUEVOS_ERROR',

    DESCARGAR_AFILIADOS_NUEVOS: 'DESCARGAR_AFILIADOS_NUEVOS',
    DESCARGAR_AFILIADOS_NUEVOS_SUCCESS: 'DESCARGAR_AFILIADOS_NUEVOS_SUCCESS',
    DESCARGAR_AFILIADOS_NUEVOS_ERROR: 'DESCARGAR_AFILIADOS_NUEVOS_ERROR',

    SET_FIRST_AFILIADO: 'SET_FIRST_AFILIADO',
    SET_LAST_AFILIADO: 'SET_LAST_AFILIADO',
    SET_PAGE: 'SET_PAGE',

    CLEAR_STATUS: 'CLEAR_AFILIADOS_STATUS',
    CLEAR_DOWNLOAD: 'CLEAR_AFILIADOS_DOWNLOAD',
    SET_NUEVO_AFILIADO_DETAILS: 'SET_NUEVO_AFILIADO_DETAILS',


    CLEAR_AFILIADOS: 'CLEAR_AFILIADO'
}

export default types