const types = {
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    AUTHENTICATE_USER_SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
    AUTHENTICATE_USER_ERROR: 'AUTHENTICATE_USER_ERROR',

    NEW_USER: 'NEW_USER',
    NEW_USER_SUCCESS: 'NEW_USER_SUCCESS',
    NEW_USER_ERROR: 'NEW_USER_ERROR',

    GET_AFILIADOS_NUEVOS: 'GET_AFILIADOS_NUEVOS',
    GET_AFILIADOS_NUEVOS_SUCCESS: 'GET_AFILIADOS_NUEVOS_SUCCESS',
    GET_AFILIADOS_NUEVOS_ERROR: 'GET_AFILIADOS_NUEVOS_ERROR',

    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',

    CLEAR_STATUS: 'CLEAR_STATUS'
}

export default types