const types = {
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    AUTHENTICATE_USER_SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
    AUTHENTICATE_USER_ERROR: 'AUTHENTICATE_USER_ERROR',

    NEW_USER: 'NEW_USER',
    NEW_USER_SUCCESS: 'NEW_USER_SUCCESS',
    NEW_USER_ERROR: 'NEW_USER_ERROR',

    GET_AFILIADOS_NUEVOS: 'GET_AFILIADOS_NUEVOS',
    GET_AFILIADOS_NUEVOS_SUCCESS: 'GET_AFILIADOS_NUEVOS_SUCCESS',
    GET_AFILIADOS_NUEVOS_ERROR: 'GET_AFILIADOS_NUEVOS_ERROR',

    SET_AFILIADOS_SIZE: 'SET_AFILIADOS_SIZE',
    SET_LAST_AFILIADO: 'SET_LAST_AFILIADO',

    CLEAR_STATUS: 'CLEAR_STATUS'
}

export default types