const types = {
    NUEVO_ENLACE: 'NUEVO_ENLACE',
    NUEVO_ENLACE_SUCCESS: 'NUEVO_ENLACE_SUCCESS',
    NUEVO_ENLACE_ERROR: 'NUEVO_ENLACE_ERROR',

    GET_ENLACES: 'GET_ENLACES',
    GET_ENLACES_SUCCESS: 'GET_ENLACES_SUCCESS',
    GET_ENLACES_ERROR: 'GET_ENLACES_ERROR',

    GET_ENLACE: 'GET_ENLACE',
    GET_ENLACE_SUCCESS: 'GET_ENLACE_SUCCESS',
    GET_ENLACE_ERROR: 'GET_ENLACE_ERROR',

    CLEAR_STATUS: 'CLEAR_STATUS'
}

export default types