const types = {
    NUEVO_ENLACE: 'NUEVO_ENLACE',
    NUEVO_ENLACE_SUCCESS: 'NUEVO_ENLACE_SUCCESS',
    NUEVO_ENLACE_ERROR: 'NUEVO_ENLACE_ERROR',

    CLEAR_STATUS: 'CLEAR_STATUS'
}

export default types