const types = {
    NUEVO_ENLACE: 'NUEVO_ENLACE',
    NUEVO_ENLACE_SUCCESS: 'NUEVO_ENLACE_SUCCESS',
    NUEVO_ENLACE_ERROR: 'NUEVO_ENLACE_ERROR',

    UPLOAD_ENLACE: 'UPLOAD_ENLACE',
    UPLOAD_ENLACE_SUCCESS: 'UPLOAD_ENLACE_SUCCESS',
    UPLOAD_ENLACE_ERROR: 'UPLOAD_ENLACE_ERROR',

    DELETE_ENLACE: 'DELETE_ENLACE',
    DELETE_ENLACE_SUCCESS: 'DELETE_ENLACE_SUCCESS',
    DELETE_ENLACE_ERROR: 'DELETE_ENLACE_ERROR',

    GET_ENLACES: 'GET_ENLACES',
    GET_ENLACES_SUCCESS: 'GET_ENLACES_SUCCESS',
    GET_ENLACES_ERROR: 'GET_ENLACES_ERROR',

    GET_ENLACE: 'GET_ENLACE',

    CLEAR_STATUS: 'CLEAR_STATUS'
}

export default types