// USER TYPES
export const UPDATE_USER = 'UPDATE_USER'

export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'

export const GET_PROFILE_EMPRESA = 'GET_PROFILE_EMPRESA'
export const GET_PROFILE_EMPRESA_SUCCESS = 'GET_PROFILE_EMPRESA_SUCCESS'
export const GET_PROFILE_EMPRESA_ERROR = 'GET_PROFILE_EMPRESA_ERROR'

export const GET_USER_BUSINESS = 'GET_USER_BUSINESS'
export const GET_USER_BUSINESS_SUCCESS = 'GET_USER_BUSINESS_SUCCESS'
export const GET_USER_BUSINESS_ERROR = 'GET_USER_BUSINESS_ERROR'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'

export const UPDATE_PROFILE_EMPRESA = 'UPDATE_PROFILE_EMPRESA'
export const UPDATE_PROFILE_EMPRESA_SUCCESS = 'UPDATE_PROFILE_EMPRESA_SUCCESS'
export const UPDATE_PROFILE_EMPRESA_ERROR = 'UPDATE_PROFILE_EMPRESA_ERROR'

export const CLEAR_PROFILE_STATUS = 'CLEAR_PROFILE_STATUS'
export const UPDATE_STEP = 'UPDATE_STEP'


